name: test-mr-cal
base: core22
version: '1.0'
summary: 'hello-world'
description: 'hello-world'
grade: devel
confinement: strict

architectures: 
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

parts:
  hello-world:
    plugin: nil
