name: Spread (manual - large/flaky)
on:
  pull_request:
    types: [labeled]
  schedule:
    - cron: "0 2 * * 0,3" # run at 2 AM on Sundays and Wednesdays

jobs:
  snap-build:
    if: ${{ github.event.label.name == 'run-manual-spread' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  snap-tests:
    if: ${{ github.event.label.name == 'run-manual-spread' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    needs: [snap-build]
    steps:
      - name: test2
        run: echo "what's going to happen?"
